// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineVideoGamePortal.Models;

namespace OnlineVideoGamePortal.Migrations
{
    [DbContext(typeof(OnlineVideoGamePortalContext))]
    [Migration("20191011005448_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineVideoGamePortal.Models.GamerInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<DateTime?>("DateJoined");

                    b.Property<string>("FavGame")
                        .HasMaxLength(250);

                    b.Property<string>("GamesPurchased");

                    b.Property<bool>("IsActiveCustomer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PreferredVideoGame")
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.ToTable("GamerInfo");
                });

            modelBuilder.Entity("OnlineVideoGamePortal.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountPaid");

                    b.Property<int>("GamerID");

                    b.Property<int?>("GamerInfoID");

                    b.Property<string>("ModeOfTransaction");

                    b.Property<int>("VideoGameID");

                    b.HasKey("PurchaseID");

                    b.HasIndex("GamerInfoID");

                    b.HasIndex("VideoGameID");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("OnlineVideoGamePortal.Models.VideoGame", b =>
                {
                    b.Property<int>("VideoGameID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("IsAvailable");

                    b.Property<bool>("IsSportsGame");

                    b.Property<int>("MemorySpace");

                    b.Property<decimal>("Price");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Version");

                    b.HasKey("VideoGameID");

                    b.ToTable("VideoGame");
                });

            modelBuilder.Entity("OnlineVideoGamePortal.Models.Purchase", b =>
                {
                    b.HasOne("OnlineVideoGamePortal.Models.GamerInfo", "GamerInfo")
                        .WithMany("Purchases")
                        .HasForeignKey("GamerInfoID");

                    b.HasOne("OnlineVideoGamePortal.Models.VideoGame", "VideoGame")
                        .WithMany("Purchase")
                        .HasForeignKey("VideoGameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
